### ISSUE TITLE
Support for 2 displays on the same espeasy device

### ISSUE THREAD

**Issue by jongerenchaos** [ThingPulse/esp8266-oled-ssd1306#107]
Thanks for this scrolling option it works OK with one display! When you add another second OLED display (3C & 3D) it doesn't work and one display displayed only the WIFI logo. Can you fix this so that everyone can use two of this displays?

**Comment by FWeinb** [comment]
You you pleas add a sketch that shows this problem in action. Otherwise we can't really help you with your problem.

**Comment by jongerenchaos** [comment]
For now i use the following build:
Build:	147
Core Version:	2_3_0

And i add 2 displays within the webconfiguration module (see all the uploaded pictures). When i restart the esp device only one of the two work. I try to made difference settings but none of all works.
I hope that this is enough information
![lcd1](https://cloud.githubusercontent.com/assets/683571/22175793/cddecb86-dffc-11e6-8355-7bfa39c059dc.png)
![lcd2](https://cloud.githubusercontent.com/assets/683571/22175795/cde30976-dffc-11e6-9873-5839412c40f2.png)
![i2cscanner](https://cloud.githubusercontent.com/assets/683571/22175794/cde24536-dffc-11e6-901a-3fcd62b4c411.png)
