### ISSUE TITLE
Support for SSD1306 64x32?

### ISSUE THREAD

**Issue by Jorgen-VikingGod** [ThingPulse/esp8266-oled-ssd1306#114]
Hi I wonder if you are planning to support the 64x32 OLED display with SSD1306 driver?
I ordered one on [aliexpress](https://www.aliexpress.com/item/0-49-inch-4PIN-White-OLED-Screen-SSD1306-Drive-IC-64-32-QT1306P24-Cable-IIC-Interface/32618313295.html?spm=2114.01010208.3.38.G34LAn&ws_ab_test=searchweb0_0,searchweb201602_2_10065_10068_433_10136_10137_10060_10062_10056_10055_10054_302_10059_10099_10103_10102_10101_10096_10052_10053_10050_10107_10051_10106_10084_10083_10119_10080_10082_10081_10110_10111_10112_10113_10114_10078_10079_10073_10070_10122_10123_10120_10126_10124,searchweb201603_9,afswitch_1_afChannel,ppcSwitch_3,single_sort_0_price_asc&btsid=3ce48ee1-e1d7-49fb-9b5e-c131c48a2382&algo_expid=003995e5-8651-4bc4-8ff7-54c4e244970c-4&algo_pvid=003995e5-8651-4bc4-8ff7-54c4e244970c)
But do not find any library to drive it on my ESP32

thx

**Comment by Djeez2** [comment]
Any progress? I'm looking for SSD1306 64x32 OLED on ESP8266.
