### ISSUE TITLE
SSD1309 support

### ISSUE THREAD

**Issue by zharijs** [ThingPulse/esp8266-oled-ssd1306#120]
Hey. The support for other drivers would involve changes to init sequence, so I would suggest it to be moved out from OLEDDisplay.cpp to SSD1306.h so new HW could be added easily. 

Here's my working SSD1309 version of your code. Use it freely, when making your new lib. Only thing you actually need from there, is the modified init sequence anyway.

[esp8266-oled-ssd1309.zip](https://github.com/squix78/esp8266-oled-ssd1306/files/972253/esp8266-oled-ssd1309.zip)

Thanks for your useful code, Harry.

**Comment by lorol** [comment]
Hello team & Harry!
This is very good idea - to add support of other SSD13xx chips like SSD1309, SSD1325, SSD1305 and SSD1322. Is there any "shortcut" guideline to get fast implementation and spend more time on testing? I have samples of all these for tests.
