### ISSUE TITLE
different font types cannot be generated

### ISSUE THREAD

**Issue by tofrnr** [ThingPulse/esp8266-oled-ssd1306#131]
different font types cannot be generated; the provided link does not load and so appears to be broken.
Currently I need a fixed_font type by different point sizes (e.g., Courier).

**Comment by squix78** [comment]
I had to restart the server. it is online again. If you agree please close
this issue...

2017-06-15 18:26 GMT+02:00 tofrnr <notifications@github.com>:

**Comment by tofrnr** [comment]
ok, I did it - 
now I get a huge file, but how to switch now in my code between the standard proportional file and the new generated 8p Courier file?
I expected something like

display.setFont(Courier, 8);
//...
display.setFont(Arial, 8);
//...
display.setFont(Courier, 20);
//...
display.setFont(Arial, 12);
//...
