### ISSUE TITLE
OLED Font generator

### ISSUE THREAD

**Issue by kfeger** [ThingPulse/esp8266-oled-ssd1306#149]
Dear squix78,
first of all: Great work! Second: Could it be, that the OLED Font Generator is offline? I get a 502 error from  http://oleddisplay.squix.ch/
Best regards!
Karl

**Comment by TD-er** [comment]
At this moment it looks to be online.

**Comment by kfeger** [comment]
Yep, ist back

Thanx!

 

Von: Gijs Noorlander [mailto:notifications@github.com] 
Gesendet: Mittwoch, 4. Oktober 2017 13:16
An: squix78/esp8266-oled-ssd1306
Cc: Karl O. Feger; Author
Betreff: Re: [squix78/esp8266-oled-ssd1306] OLED Font generator (#149)

 

At this moment it looks to be online.

**Comment by kfeger** [comment]
BTW: Enjoy the beer!

Cheers!

 

Von: Gijs Noorlander [mailto:notifications@github.com] 
Gesendet: Mittwoch, 4. Oktober 2017 13:16
An: squix78/esp8266-oled-ssd1306
Cc: Karl O. Feger; Author
Betreff: Re: [squix78/esp8266-oled-ssd1306] OLED Font generator (#149)

 

At this moment it looks to be online.

**Comment by Oliverr** [comment]
Down again

**Comment by cryptooth** [comment]
Could you add DSEG7_Classic smaller size fonts?

**Comment by Masoud-Ebrahimi** [comment]
Hello,
Please see my free developed projects for OLEDH : OLED image to Hex :
https://elvand.com/oledh/
And LCD Font Generator LFG :
https://elvand.com/lcd-font-generator-lfg/

It's my pleasure to have your suggestions.

With best regard.
