### ISSUE TITLE
'SSD1306 {aka class SSD1306Wire}' has no member named 'mirrorScreen'

### ISSUE THREAD

**Issue by rin67630** [ThingPulse/esp8266-oled-ssd1306#182]
The Doc mentions the function, but it seems not to be operative yet, compiled with Arduino IDE.

That function would be wery much appreciated. Thank you.

**Comment by squix78** [comment]
The doc refers to the current development version. The mirror function will be available with the next release (4.0.0). You can however download the current version as zip and install it manually. Testers are welcome!
