### ISSUE TITLE
More drawn pixels the lower the contrast

### ISSUE THREAD

**Issue by high500** [ThingPulse/esp8266-oled-ssd1306#194]
Hi all

I did try to see if there was a similar issue, but nothing appeared to match my exact problem.

I have to power my oled direct from a 5v source (3.3v from esp wasn't sufficient).
If I write a small amount of text the display is a brilliant bright which is perfect. Once I start adding more and more pixels either xbm images or just text, the contrast lowers and flickering occurs. This increases with the more pixels I write to the screen, the darker the display.

The strange thing is when I write my code to my esp using Arduino IDE the second the flash process starts the contrast is back to brilliant bright white whatever the pixel count.

Am I missing something? is my ESP drawing power away from the oled in some way? I have checked my code to ensure I haven't set any of the pins I am using to anything else and they are definatley not.

The only pin I am using is gpio16 --> pin 0 but i even commented out the code just in case. no luck (as expected)

Any input would be appreciated

Stewart

**Comment by lorol** [comment]
Try to power OLED from a separate 5 to 3V3 regulator. Do not use directly
your 5V.
Measure the total current draw and see if your source can actually handle
it. Most-likely it just cranks when you light more dots.
