### ISSUE TITLE
Text Rotation

### ISSUE THREAD

**Issue by suculent** [ThingPulse/esp8266-oled-ssd1306#204]
Hello, would it be possible to add a 90 degree text rotation? 
I can imagine it’s a bitwise operation instead of bytewise masking and it could be very slow even if the font was pre-rendered as rotated.

**Comment by lionzan** [comment]
Also here, it would be great for any project using the display in vertical orientation. Any plans on doing it? (I tried but it's beyond me...)

**Comment by bsvdoom** [comment]
b

**Comment by dgrahn** [comment]
I'd also be interested in this.
