### ISSUE TITLE
Different line break behavoir between drawString and drawStringMaxWitdh

### ISSUE THREAD

**Issue by dve** [ThingPulse/esp8266-oled-ssd1306#218]
If you use `drawString` a line break in the string is a line break on the display.
In the `drawStringMaxWidth` its ignored.

**Comment by ketan** [comment]
I'm seeing the same issue:

```
display.drawStringMaxWidth(0, 0, 128, "Lorem ipsum\n dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore.");
```

Seems to display the following on a 0.96inch oled:

![IMG_20190323_091115](https://user-images.githubusercontent.com/10598/54861247-0c41c180-4d4c-11e9-9dcb-06c8a7b8ef01.jpg)
