### ISSUE TITLE
Typo or not documented function in SSD1306SimpleDemo "ipsum\n" 

### ISSUE THREAD

**Issue by Nobuo1** [ThingPulse/esp8266-oled-ssd1306#224]
In SSD1306SimpleDemo 

    display.setFont(ArialMT_Plain_10);
    display.setTextAlignment(TEXT_ALIGN_LEFT);
    display.drawStringMaxWidth(0, 0, 128,
      "Lorem ipsum\n dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore." );

I wonder if "\n" is documented anywhere which other similar functions

**Comment by tuxBurner** [comment]
Hmmm why document this. 
This is in general  LF (Line Feed) in most string handling.

Or do you mean that the display can handle those ?

**Comment by Joennuh** [comment]
Maybe the documentation could see the functions do support line feed but actually it is a generally known character combination.
