### ISSUE TITLE
Rotation ?

### ISSUE THREAD

**Issue by vtomanov** [ThingPulse/esp8266-oled-ssd1306#227]
Hello,

I want to use the display vertically ( e.g. 64x128) any idea how this can be done with the library ?

Thanks

**Comment by Joennuh** [comment]
It would indeed be great to have the possibility to use the screen vertically.

**Comment by vtomanov** [comment]
The Adafruit lib which is pretty the sane has Rotation which does exactly this - should easy to be added to this lib also.. in my new project the screen is vertical in the enclosure.

**Comment by captFuture** [comment]
I was exactly searching for the same thing because i want to use a 128x64 screen vertically

**Comment by marcelstoer** [comment]
Duplicate of #204
