### ISSUE TITLE
Degree symbol is not shown

### ISSUE THREAD

**Issue by WilkoV** [ThingPulse/esp8266-oled-ssd1306#230]
The library does not show the degree symbol (°) if I add it to a String or char array. Is there a way to show the symbol?)

**Comment by ITEnDev** [comment]
Hi.
Try to use the following:
`display.drawString(0, 15, "H: " + String(temperature0ValueToDisplay) + "/" + String(temperature1ValueToDisplay) + " °C");`
It is works for me. 
In this example I used two variables (temperature0ValueToDisplay and temperature1ValueToDisplay) and two fixed tag ("/" and  " °C") to displaying in a line on the display.

I hope this will help.
