### ISSUE TITLE
Exists an example for text scrolling?

### ISSUE THREAD

**Issue by davidwowa** [ThingPulse/esp8266-oled-ssd1306#231]
Hi, 

exists an example for text scrolling?

thx

**Comment by Joennuh** [comment]
[SSD1306DrawingDemo.ino](https://github.com/ThingPulse/esp8266-oled-ssd1306/blob/master/examples/SSD1306DrawingDemo/SSD1306DrawingDemo.ino) contains a vertical scrolling text. Maybe that does fit your needs?
If you are searching for a horizontal scrolling text: I haven't found a solution for that yet and I'm also wondering how that could be implemented with this library.

**Comment by davidwowa** [comment]
thx
