### ISSUE TITLE
The double buffering bitmap display update can be highly optimised

### ISSUE THREAD

**Issue by helmut64** [ThingPulse/esp8266-oled-ssd1306#242]
My understanding is that at present the single largest rect containing the changes will be calculated, than this entire rect is transferred to the display.

One enhancement would be to spilt this rect into smaller chunks (e.g. 16x16 pixel) and write only the chunks with changes to the display.

**Comment by helmut64** [comment]
I believe I raised the point, I close this enhancement for now.

**Comment by marcelstoer** [comment]
I already removed the stale flag a couple of days ago because I think you raised a valid point. I can't guarantee though that we'll get around to fixing this before the bot comes by in 180d 😉
