### ISSUE TITLE
Overwrite one line as string

### ISSUE THREAD

**Issue by davidwowa** [ThingPulse/esp8266-oled-ssd1306#244]
In my display I have seven lines with different value, there are refresh in different time. I must every time run display.clear(), but I will refresh only one line from seven, it is possible? thx

**Comment by beast099** [comment]
you can utilize the fillRect function to essentially clear a single line.

if your using the ArialMT_Plain_10 font, which is 10 pixels in height then something like:

```
display.setColor(BLACK);
display.fillRect(0, 0, 128, 10);
display.display();
display.setColor(WHITE);
```

will "clear" the first line
 
`display.fillRect(0,10,128,10);`

will "clear" the second line
and so on.
