### ISSUE TITLE
Font with diacritics ?

### ISSUE THREAD

**Issue by DaTTcz** [ThingPulse/esp8266-oled-ssd1306#250]
Hello, how can I add a font with support for diacritic? If I am create a font with 382 characters, it will streak and spilled on the display. Only works if the font is 255 characters long. How can I add font for diacritic char ? (ěščřžýáíéúů...) I use this Glyph Editor - https://rawgit.com/lorol/esp8266-oled-ssd1306/master/resources/glyphEditor.html Thank you and sorry for my english.

**Comment by colesnicov** [comment]
Any progress  in the supports for the Czech language? 

@DaTTcz,  Nejaky pokrok s cestinou?
