### ISSUE TITLE
Dual displays

### ISSUE THREAD

**Issue by prabbit237** [ThingPulse/esp8266-oled-ssd1306#255]
This isn't an issue as much as a suggested change to the sample code. You have an example of using two different displays with the same I2C address on a single esp8266 but the sample is showing using 4 separate pins (and the esp8266 doesn't have as many GPIO pins as people would like.)

    SSD1306Wire  display(0x3c, D3, D5);
    SSD1306Wire  display2(0x3c, D1, D2);

 But a quick test shows you can actually do it with three pins:

    SSD1306Wire  display(0x3c, D4, D3);
    SSD1306Wire  display2(0x3c, D2, D3);

That setup is working great on a NodeMCU v1.0 board and saved one pin (the project I'm working on was starting to run short on usable GPIO's and I didn't want to start grabbing the TX/RX pins.) Sharing the SDA and using separate SCL pins also works fine. So you may want to show both ways in the example code.

**Comment by marcelstoer** [comment]
Sure, why not. Can you prepare a PR for that maybe also mentions such a setup in the README?
