### ISSUE TITLE
oled not working

### ISSUE THREAD

**Issue by hoahoctro** [ThingPulse/esp8266-oled-ssd1306#266]
I tried many libs else, but always get noise with nothing 
i dont know why, i tried 4.7k Ohm pull up too but still be

![image](https://user-images.githubusercontent.com/33972583/69909104-3cd41200-1428-11ea-8da4-10187b92f719.png)

**Comment by 4kuato** [comment]
Hi @hoahoctro, check this: https://luma-oled.readthedocs.io/en/latest/troubleshooting.html
You need to use the SH1106 driver.

**Comment by fk0** [comment]
I'm seeing the same image on SH1106 driver. Any other ideas how to get it working?
