### ISSUE TITLE
images.h is no longer part of lib headers but still shows on platformio registry

### ISSUE THREAD

**Issue by italomaia** [ThingPulse/esp8266-oled-ssd1306#285]
As seen here: https://platformio.org/lib/show/2978/ESP8266%20and%20ESP32%20OLED%20driver%20for%20SSD1306%20displays/headers

**Comment by marcelstoer** [comment]
Not sure how PlatformIO scans for headers but `images.h` are part of the demos e.g. https://github.com/ThingPulse/esp8266-oled-ssd1306/blob/master/examples/SSD1306UiDemo/images.h
