### ISSUE TITLE
How about adding setTextColor() Function?

### ISSUE THREAD

**Issue by yammayamm** [ThingPulse/esp8266-oled-ssd1306#287]
Why don't you have setTextColor(FontColor,BackgroundColor) function? I was trying to use this function to display the inverted text for my project, but I couldn't use it. It seems that you don't have basic function of changing text color neither.

Adafruit_SSD1306 has this function. See this link.
(https://github.com/adafruit/Adafruit_SSD1306/blob/master/examples/ssd1306_128x64_i2c/ssd1306_128x64_i2c.ino)

Can you add this function? Thx :)

**Comment by sjly3k** [comment]
Cool :) I found this function in this package but I couldn't. If this function works in this package, All users who use this package can make more fancier haha XD

**Comment by marcelstoer** [comment]
> Why don't you have setTextColor(FontColor,BackgroundColor) function?

We don't need it and nobody else requested it so far. However, we would certainly welcome PR to that effect by you or somebody else.

**Comment by SVLoneStar** [comment]
Hi - sure, this is not desperately needed. But it would be nice to be able to show lines of 'inverted' text on the display.
Any other means to do this? If not, implementing this feature would be highly appreciated (by me). Thanks!

**Comment by turbofex** [comment]
vote yes on set text color,very useful when making menus.

**Comment by turbofex** [comment]
found a way around this.draw the strings,then call setColor(INVERSE) and fillRect() over the text area would do a inverted text effect.works for me.
U could give it a try. @yammayamm

**Comment by yammayamm** [comment]
Thnks :)
