### ISSUE TITLE
Error with SH1106

### ISSUE THREAD

**Issue by Cyb3rn0id** [ThingPulse/esp8266-oled-ssd1306#303]
In the demos there is written:

`// SH1106 display(0x3c, SDA, SCL);     // ADDRESS, SDA, SCL`

must be

`// SH1106Wire display(0x3c, SDA, SCL);     // ADDRESS, SDA, SCL`

**Comment by marcelstoer** [comment]
We accept and appreciate PRs with fixes. Could you help us out here?

**Comment by Rotzbua** [comment]
@marcelstoer Same as #338, fixed with #340
