### ISSUE TITLE
wemos d1 esp8266 how to connect with ssd1306

### ISSUE THREAD

**Issue by borborich** [ThingPulse/esp8266-oled-ssd1306#306]
I can't find how to connect ssd1306 with wemos D1
with d4 d5 not worked.
Anybody can help me, give me some example (how to connect)?
Thank you
![IMG_1012](https://user-images.githubusercontent.com/38986985/94347857-2db5f480-0038-11eb-8a4e-8758f7bec12c.JPG)

**Comment by tokra** [comment]
You have to connect it to SCL and SDA, and so use => D15 = SCL, D14 = SDA

**Comment by borborich** [comment]
> @borborich You have to connect it to SCL and SDA, and so use => D15 = SCL, D14 = SDA

thank you
