### ISSUE TITLE
SSD1306 OLED not working with Thingpulse library (but with olikraus one)

### ISSUE THREAD

**Issue by mbobinger** [ThingPulse/esp8266-oled-ssd1306#311]
Hi Guys,

I've followed this github project and wanted to build a lorawan tracker:
https://github.com/kizniche/ttgo-tbeam-ttn-tracker

using a noname SSD1306 OLED from amazon:
https://www.amazon.de/AZDelivery-Display-Arduino-Raspberry-Gratis/dp/B078J78R45

I've verified that the OLED works with following library, as suggested by the distributor:
https://github.com/olikraus/u8g2

However, the display just outputs bullshit when using the thingpulse library examples or the code in the github repo:
https://github.com/ThingPulse/esp8266-oled-ssd1306

Is there any software fix for this, is the hardware different?

I'm using this board: https://github.com/LilyGO/TTGO-T-Beam
Thank you!

**Comment by marcelstoer** [comment]
Also see #327
