### ISSUE TITLE
Wemos D1 mini oled shield support

### ISSUE THREAD

**Issue by tokra** [ThingPulse/esp8266-oled-ssd1306#312]
Is this lib supporting 64x48 oled ?

When i used this lib: display.getWidth() gives me 128, display.getHeight() 64. Display works but it prints out of bounds.
It needs 64x48 setting.

https://docs.wemos.cc/en/latest/d1_mini_shiled/oled_0_66.html

**Comment by marcelstoer** [comment]
See #198

**Comment by tokra** [comment]
@marcelstoer thx, I just saw PR wasnt merged, and was closed. so Im using his repo for now.

**Comment by rin67630** [comment]
Issue solved, thank you!
