### ISSUE TITLE
Change I2C address of SH1106 128x64 OLED

### ISSUE THREAD

**Issue by e-labInnovations** [ThingPulse/esp8266-oled-ssd1306#315]
I have a 1.3 inch I2C SH1106 128x64 pixel OLED. I can't find any resistor responsible for I2C address. 
Please help me to change I2C address of this display
![](https://i.imgur.com/vXHaebX.jpg)

**Comment by marcelstoer** [comment]
This issue is unrelated to this project -> closing

**Comment by xrayer2000** [comment]
I have the exaxt same oled, and i wonder too
