### ISSUE TITLE
Printing text without last pixel position

### ISSUE THREAD

**Issue by tokra** [ThingPulse/esp8266-oled-ssd1306#316]
Is there a method like in Adafruit library where u dont need to add cordinates to print string ?
I only set position of 1st cursor then called print. It would be very useful to know as not everytime u know position of last printed text cursor. for example when Im printing dots "." in while loop when connecting to wifi.
thank you in advance

**Comment by TheOnlyGoodOne** [comment]
You can use this example for a simple ". . .":
```c++
  int i = 0;
  display.drawString(0, 0, "Connecting");
  while (WiFi.status() != 3) {
    if (i > 8) {
      i = 0;
      display.clear();
      display.drawString(0, 0, "Connecting");
      display.display();
    } else {
      display.drawString(i * 8 + 85, 0, ".");
      display.display();
      i++;
      delay(250);
    }
    WiFi.begin("MyNetwork", "MyPass123");
  }
```
