### ISSUE TITLE
Wrong esp8266-oled-ssd1306 library definition on Platformio

### ISSUE THREAD

**Issue by netmaniac** [ThingPulse/esp8266-oled-ssd1306#333]
Hi!
I guess this is problem with library definition on platfromio, not platformio bug itself, so I report it here.

With library name change on platfomio older release got lost. So, only 4.2.0 can be installed via platformio. To reproduce

create new project (pio init --ide=clion --board=nodemcuv2) and use platformio.ini:

```
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
lib_ldf_mode = chain+
lib_deps=562@4.1.0

```

Then `pio run` will produce following warning:
```
Library Manager: Installing id:562 @ 4.1.0
Warning! Could not find the package with 'id:562 @ 4.1.0' requirements for your system 'linux_x86_64'
```
Changing to 4.2.0 will install dependency.

**Comment by marcelstoer** [comment]
I raised an issue on their forum asking for advice how to proceed. Result: they completely deleted 562 w/o even asking back 😞 

You can either install `2978 @ 4.1.0` or `2978 @ 4.2.0`. I will update the README accordingly.

P.S. If you search for '562' at https://platformio.org/lib they still list this library, but under the "new" id. What a mess.
