### ISSUE TITLE
Small fix on some examples

### ISSUE THREAD

**Issue by Edduaardo** [ThingPulse/esp8266-oled-ssd1306#338]
**Describe the bug**
In some examples, when declaring a SH1106 display some examples are using SH1106 instead of SH1106Wire class and recommending to import the SH1106Wire.h header, and since the SH1106 class doesn't exist on SH1106Wire.h header, it errors out. Since the recommended is the SH1106Wire now I created a branch with the fix on the examples.

**Comment by marcelstoer** [comment]
Pull requests with fixes are always welcome.

**Comment by Edduaardo** [comment]
Openined a Pull Request with the fixes #340
