### ISSUE TITLE
Fade in/out display

### ISSUE THREAD

**Issue by thijstriemstra** [ThingPulse/esp8266-oled-ssd1306#351]
How can I fade in/out the display?

**Comment by illosan** [comment]
Fadein:

  for (int i = 0; i < 256; i++) {
    d1306.setBrightness(i);
    d1306.display();
    delay(2);
  }

Fadeout:

  for (int i = 255; i >= 0; i--) {
    d1306.setBrightness(i);
    d1306.display();
    delay(4);
  }

**Comment by thijstriemstra** [comment]
thanks!
