### ISSUE TITLE
Using SSD1306Wire with multi-core ESP32 

### ISSUE THREAD

**Issue by jerryg2003** [ThingPulse/esp8266-oled-ssd1306#352]
Just a note on how I got a multi-core ESP32 sketch using display functions to work properly.   

I had successfully used SSD1306Wire with arduinos and was starting to use with ESP32s.  I have a multi-task sketch to which I wanted to add display functions.  Adding a start-up display of text and graphics in the setup() function worked like a charm.  However, when I tried to clear and display some other text in a different task, the display only partially cleared and the text didn’t start in the place it was supposed to.  After much experimenting (and hair-pulling), I tried changing the core my work task was running in and all worked fine.  My prior setup had the work task in core 0 while the setup() had run in core 1.  I’m not sure why this would have made a difference (both cores reference the same memory), but changing the work task to also run in task 1 solved the problem with the display clearing and the text drawing correctly.

FYI, I am using the arduino IDE.

Thanks for making this software available.

**Comment by thijstriemstra** [comment]
Also see #326
