### ISSUE TITLE
SSD1306Wire.h, line 145 causes compilation error  'byte' is ambiguous

### ISSUE THREAD

**Issue by neutralvibes** [ThingPulse/esp8266-oled-ssd1306#383]
**Describe the bug**
Using 'byte' in SSD1306Wire.h, line 145 causes compilation error  'byte' is ambiguous error in my case.
~~~c++
        byte k = 0;
        for (y = minBoundY; y <= maxBoundY; y++) {
          for (x = minBoundX; x <= maxBoundX; x++) {
            if (k == 0) {
~~~

**Expected behavior**
Use of `uint8_t` 

~~~c+++
        uint8_t k = 0;
~~~

**Versions (please complete the following information):**
 - Library: 4.40
 - Platform: ESP266 Arduino

**Comment by marcelstoer** [comment]
Even though I cannot reproduce this here it would make sense to replace the 4 places someone used `byte` with `uint8_t`. Seems related to https://github.com/esp8266/Arduino/pull/8090.
