### ISSUE TITLE
Add ability to specifying different frame times. 

### ISSUE THREAD

**Issue by Craig1516** [ThingPulse/esp8266-oled-ssd1306#91]
The intention of the subject function is to vary the presentation time of different frames, say each of three.   To do so, I tried the command  "ui.setTimePerFrame(5000);"  in one frame then the same command in two other frames, only with different times.  I followed the structure of "ui.*" for other commands that worked successfully for me, like "ui.disableIndicator();"  The documentation doesn't give much to go on and this function is not represented in the examples.  So if I did this right my project is attached for anyone's use.  Hope it helps.

[TriMetDisplayMod1.txt](https://github.com/squix78/esp8266-oled-ssd1306/files/569646/TriMetDisplayMod1.txt)
[images.txt](https://github.com/squix78/esp8266-oled-ssd1306/files/569647/images.txt)

**Comment by FWeinb** [comment]
Thanks for raising this question. This library currently doesn't support different times for each frame. I will leave this open and attach it to the 4.0.0 milestone so we can work an adding this feature.
